"""add food_servings table and meal_entry unit fields

Revision ID: 95b739f437cd
Revises: 8a09e0e2e034
Create Date: 2026-03-28 14:38:10.271586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b739f437cd'
down_revision: Union[str, Sequence[str], None] = '8a09e0e2e034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_servings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('serving_description', sa.String(length=200), nullable=False),
    sa.Column('serving_size_g', sa.Float(), nullable=False),
    sa.Column('metric_serving_amount', sa.Float(), nullable=True),
    sa.Column('metric_serving_unit', sa.String(length=10), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_servings_food_item_id'), 'food_servings', ['food_item_id'], unique=False)
    op.create_index(op.f('ix_food_servings_id'), 'food_servings', ['id'], unique=False)
    op.add_column('meal_entries', sa.Column('serving_unit', sa.String(length=20), nullable=True))
    op.add_column('meal_entries', sa.Column('serving_quantity', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # Trigram index for faster food name search (PostgreSQL only)
    try:
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        op.execute(
            "CREATE INDEX ix_food_items_name_trgm ON food_items "
            "USING gin (name gin_trgm_ops)"
        )
    except Exception:
        pass  # SQLite dev — skip


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_entries', 'serving_quantity')
    op.drop_column('meal_entries', 'serving_unit')
    op.drop_index(op.f('ix_food_servings_id'), table_name='food_servings')
    op.drop_index(op.f('ix_food_servings_food_item_id'), table_name='food_servings')
    op.drop_table('food_servings')
    # ### end Alembic commands ###
